### ISSUE TITLE
What does "Certificate" mean

### ISSUE THREAD

**Issue by bradynpoulsen** [getsentry/sentry-phabricator#3]
There's nothing that explains what the plugin wants for a certificate.. I gave it a private rsa key generated by phabricator and it failed. I gave it an API Token and it failed..

What does it want? And is there anything documenting this?

Thanks

**Comment by pzinovkin** [comment]
Same question. @dcramer ?

**Comment by dcramer** [comment]
I dont know if Phabricator has changed (I haven't used it in a year), but the certificate was how authentication used to work.

**Comment by pzinovkin** [comment]
I just tried to setup integration with phabricator at app.getsentry.com and there is also "Certificate" field.
From what I see in my phabricator instance it now uses Conduit API Tokens.

**Comment by andrew-dixon** [comment]
Have the same issue.

**Comment by andrew-dixon** [comment]
@dcramer - Can you explain how you generate a certificate? After spending some time looking there appears to be a function to call to get a certificate by visiting:

http://my-phabricator-install/conduit/method/conduit.getcertificate/

However after completing the fields with what I think is right I just get a message saying the token is not valid.

Thanks

**Comment by dcramer** [comment]
@andrew-dixon we are going to need to update this extension I believe. It's possible that you cannot easily generate the same credentials as were previously needed.

**Comment by andrew-dixon** [comment]
@dcramer - I would be willing to help with anything I can, probably testing as I'm not very up to speed with Python, let me know what I can do.

**Comment by rrfeng** [comment]
How is it going on？I has successfully configured this plugin，but now I can't.

**Comment by andrew-dixon** [comment]
@dcramer Thanks for the update, works well.
